/*
 * File: app/view/MainNav.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CityBars.view.MainNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainnav',

    config: {
        tpl: [
            '<img class="photo" src="',
            '{photo_url}" width="100"',
            'height="100"/>',
            '  <h2>{name}</h2>',
            '  <div class="info">',
            '  {address1}<br/>',
            '  <img src="',
            '{rating_img_url_small}"/>',
            '</div>'
        ],
        navigationBar: {
            ui: 'light'
        },
        items: [
            {
                xtype: 'container',
                id: 'listCard',
                layout: {
                    type: 'fit'
                },
                title: 'Restaurants',
                items: [
                    {
                        xtype: 'list',
                        id: 'dataList',
                        itemTpl: [
                            '<img class="photo"',
                            'src="{photo_url}"',
                            'width="40" ',
                            'height = "40"/>{name}',
                            '<br/>',
                            '<img ',
                            'src="{rating_img_url_small}"/>&nbsp;<small>{address1}<br/>{city}, {state_code}</small>'
                        ],
                        store: 'BusinessStore'
                    }
                ]
            }
        ]
    }

});