package hello;
// Generated Oct 13, 2010 12:51:48 PM by Hibernate Tools 3.2.0.beta8



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {

    // Fields    

     private long messageId;
     private String messageText;
     private Long nextMessageId;

     // Constructors

    /** default constructor */
    public Messages() {
    }

	/** minimal constructor */
    public Messages(long messageId) {
        this.messageId = messageId;
    }
    /** full constructor */
    public Messages(long messageId, String messageText, Long nextMessageId) {
       this.messageId = messageId;
       this.messageText = messageText;
       this.nextMessageId = nextMessageId;
    }
   
    // Property accessors
    public long getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }
    public String getMessageText() {
        return this.messageText;
    }
    
    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    public Long getNextMessageId() {
        return this.nextMessageId;
    }
    
    public void setNextMessageId(Long nextMessageId) {
        this.nextMessageId = nextMessageId;
    }




}


