
package brownbagclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempConvertImplService", targetNamespace = "http://provider.brownbag.jws.johnragan.org/", wsdlLocation = "http://127.0.0.1:9876/jws/tempconvert?wsdl")
public class TempConvertImplService
    extends Service
{

    private final static URL TEMPCONVERTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(brownbagclient.TempConvertImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = brownbagclient.TempConvertImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9876/jws/tempconvert?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9876/jws/tempconvert?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEMPCONVERTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TempConvertImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvertImplService() {
        super(TEMPCONVERTIMPLSERVICE_WSDL_LOCATION, new QName("http://provider.brownbag.jws.johnragan.org/", "TempConvertImplService"));
    }

    /**
     * 
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertImplPort")
    public TempConvert getTempConvertImplPort() {
        return super.getPort(new QName("http://provider.brownbag.jws.johnragan.org/", "TempConvertImplPort"), TempConvert.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertImplPort")
    public TempConvert getTempConvertImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://provider.brownbag.jws.johnragan.org/", "TempConvertImplPort"), TempConvert.class, features);
    }

}
